version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    default_labels:
    - "dependencies"
  - package_manager: "php:composer"
    directory: "/"
    update_schedule: "daily"
    default_labels:
    - "dependencies"
